
macro(maketests)
    if (NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        return()
    endif()
    file(GLOB testfiles ${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cc)
    foreach(testfile IN LISTS testfiles)
        get_filename_component(tname ${testfile} NAME_WE)
        set(tname "${PROJECT_NAME}-test-${tname}")
        message(NOTICE ">>>> Add test [${tname}]")
        add_executable(${tname} ${testfile})
        target_link_libraries(${tname} PRIVATE ${PROJECT_NAME})
    endforeach(testfile)
endmacro()